# Generated by Django 5.0.14 on 2025-11-07 05:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('host_control', models.BooleanField(default=False)),
                ('host_username', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
