# Generated by Django 5.0.14 on 2025-11-07 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.FloatField(default=0.0)),
                ('is_playing', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Room State',
                'verbose_name_plural': 'Room States',
            },
        ),
    ]
