# Generated by Django 5.0.14 on 2025-11-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_video_room_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Rating (0.0-10.0)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='year',
            field=models.IntegerField(blank=True, help_text='Release year', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, help_text='Short description', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='source_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('direct', 'Direct Link'), ('screen_share', 'Screen Share'), ('uploaded', 'Uploaded File')], default='direct', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
